### ISSUE TITLE
Are below lines really necessary in the net architecture?

### ISSUE THREAD

**Issue by kingofoz** [siavashk/imagenet-autoencoder#1]
self.net:add(nn.Reshape(24 \* 16 \* 16))
  self.net:add(nn.Linear(24 \* 16 \* 16, 1568))
  self.net:add(nn.Linear(1568, 24 \* 16 \* 16))
  self.net:add(nn.Reshape(24, 16, 16))

I removed them and seems network can still be trained.

**Comment by siavashk** [comment]
If you remove all four lines, there is no encoding happening. The network is simply a convolution followed by a deconvolution. You can still train a network, but I do not think it would be useful. Basically there is no abstraction happening.

On my machine, removing reshape layers without removing linear layers results in the error below:

/torch/install/bin/luajit: torch/install/share/lua/5.1/nn/Linear.lua:54: input must be vector or matrix
stack traceback:
    [C]: in function 'error'
    /torch/install/share/lua/5.1/nn/Linear.lua:54: in function 'updateOutput'
    /torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
    .../torch/install/share/lua/5.1/nn/StochasticGradient.lua:35: in function 'train'
    scripts/train.lua:47: in main chunk
    [C]: in function 'dofile'
    /torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x004065d0

**Comment by kingofoz** [comment]
I see. nn.Linear() trys to compress something? How 1568 comes, can I try different value instead?

**Comment by kingofoz** [comment]
And, I am using test.lua to test the trained model(trained without the 4 lines). Seems the learned images are pretty good. Is this normal?

**Comment by siavashk** [comment]
`y = nn.Linear(x, W)` is simply a matrix multiplication, i.e. `y = W * x`. 1568 is about a quarter of 24 x 16 x 16, so I am basically compressing the features from the previous layer by a factor of 4. You can experiment with this number, and see how the autoencoder performs.

**Comment by kingofoz** [comment]
Thanks. I am doing some experiments and I will update with you if I have more questions.
