### ISSUE TITLE
The gap between training and validation errors

### ISSUE THREAD

**Issue by kingofoz** [siavashk/imagenet-autoencoder#3]
Hi Siavash,
I made some changes to imagenet-autoencoder and trained it. After some rounds, I get 0.003 for training error and 0.013 for validation error. I feel the gap between them is big, is the autoencoder in overfitting status?

**Comment by siavashk** [comment]
First, keep in mind that training error will always be (hopefully slightly) lower than validation error. Also, autoencoders that have a smaller hidden layer compared to input data perform similar to lossy compression. This difference could be a result of these two factors.

**Comment by kingofoz** [comment]
I see. Thank you! So the gap in my scenario is 0.01, it is not big, right?

**Comment by siavashk** [comment]
On average, you have a 0.01 error for any reconstructed pixel. Each pixel is a floating number between 0 and 1. This is quite small.

**Comment by kingofoz** [comment]
ah! I understand now. Thanks for the informative answer!
