### ISSUE TITLE
Line #28 in autoencoder.lua

### ISSUE THREAD

**Issue by kingofoz** [siavashk/imagenet-autoencoder#4]
Hi @siavashk 
I have a question, please see line #28:
https://github.com/siavashk/imagenet-autoencoder/blob/master/core/autoencoder.lua#L28

self.net:add(nn.SpatialConvolution(12, 12, 3, 3, 1, 1, 1, 1))

You see, 12 in and 12 out. So we have the same number of the input and the output, what effect will this layer actually do?

Thanks,
Yingjun

**Comment by siavashk** [comment]
There is a non-linear element between the two layers, so the combination of the two layers cannot be represented by a single linear layer. This layer provides a more abstract representation of the network input. Note that to get a higher order representation, you need not necessarily have more/less number of outputs.

**Comment by kingofoz** [comment]
I see. Let me try to say it in my word. :-)
The output of line #28 is a higher order representation of the input. It adds the non-linear factor to the network. Is this correct?
I tried to remove the layer of line #28, and the network indeed became difficult to converge.
I have a question, if I add one more layer, for example: self.net:add(nn.SpatialConvolution(24, 36, 3, 3, 1, 1, 1, 1)) after layer #31: self.net:add(nn.SpatialConvolution(12, 24, 3, 3, 1, 1, 1, 1), do we still need a layer self.net:add(nn.SpatialConvolution(24, 24, 3, 3, 1, 1, 1, 1)) between the two layers?

Thanks!
Yingjun

**Comment by siavashk** [comment]
Probably not. To the best of my knowledge, selecting the number of filters for convolution layers is still experimental. The best strategy for selecting these numbers is not known.

**Comment by kingofoz** [comment]
I see. Thanks!!
